//data for all rich people
var richPeopleData = {
	"people":[
		{
			"id":69420,
			"name":"Bill Gates",
			"netWorth":"1.1e11",
			"occupation":"rich",
			"chonkiness":"5",
			"companies":[12345],
			"alphaLevel":"2",
			"attractiveness":"10",
		},
		{
			"id":89564,
			"name":"Jeff Bezos",
			"netWorth":"1.1e11",
			"occupation":"CEO of Amazon",
			"chonkiness":"10",
			"companies":[23456,88888],
			"alphaLevel":"8",
			"attractiveness":"6",
		},
		{
			"id":50568,
			"name":"Warren Buffett",
			"netWorth":"8.7e10",
			"occupation":"makes money",
			"chonkiness":"9",
			"companies":[89012],
			"alphaLevel":"7",
			"attractiveness":"6",
		},
		{
			"id":07984,
			"name":"Bernard Arnault",
			"netWorth":"1.0e11",
			"occupation":"CEO boi",
			"chonkiness":"5",
			"companies":[90123],
			"alphaLevel":"3",
			"attractiveness":"3",
		},
		{
			"id":94406,
			"name":"Mark Zuckerberg",
			"netWorth":"7.4e10",
			"occupation":"not being a robot",
			"chonkiness":"6",
			"companies":[67890],
			"alphaLevel":"10",
			"attractiveness":"3",
		},
		{
			"id":16131,
			"name":"Amancio Ortega",
			"netWorth":"7.7e10",
			"occupation":"fashion dude",
			"chonkiness":"3",
			"companies":[01234],
			"alphaLevel":"3",
			"attractiveness":"0",
		},
		{
			"id":35029,
			"name":"Larry Ellison",
			"netWorth":"6.9e10",
			"occupation":"having a fine mustache",
			"chonkiness":"3",
			"companies":[78901],
			"alphaLevel":"7",
			"attractiveness":"7",
		},
		{
			"id":56544,
			"name":"Donald Trump",
			"netWorth":"3.1e9",
			"occupation":"professional tweeter",
			"chonkiness":"9001",
			"companies":[15973],
			"alphaLevel":"69",
			"attractiveness":"-1000000000",
		},
		{
			"id":86243,
			"name":"Larry Page",
			"netWorth":"5.7e10",
			"occupation":"unemployed",
			"chonkiness":"5",
			"companies":[56789],
			"alphaLevel":"2",
			"attractiveness":"2",
		},
		{
			"id":09138,
			"name":"Carlos Slim",
			"netWorth":"7.6e10",
			"occupation":"being slim",
			"chonkiness":"1",
			"companies":[13579],
			"alphaLevel":"2",
			"attractiveness":"1",
		},
		{
			"id":98254,
			"name":"Mukesh Ambani",
			"netWorth":"6.1e10",
			"occupation":"business man",
			"chonkiness":"10",
			"companies":[24680],
			"alphaLevel":"8",
			"attractiveness":"7",
		},
		{
			"id":45233,
			"name":"Sergey Brin",
			"netWorth":"5.3e10",
			"occupation":"google",
			"chonkiness":"10",
			"companies":[56789],
			"alphaLevel":"8",
			"attractiveness":"10",
		},
	],
	"companies":[
		{"id":12345,
			"name":"microsoft",
			"stonks":"3.3e10",
			"employees":"1.5e5",
			"description":"making computers and windows",
			"logo": 'https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE2qVsJ?ver=3f74',
		},
		{"id":23456,
			"name":"amazon",
			"stonks":"6.9e12",
			"employees":"7.5e5",
			"description":"not paying taxes",
			'logo': 'https://media.corporate-ir.net/media_files/IROL/17/176060/Oct18/Amazon%20logo.PNG',
		},
		{"id":34567,
			"name":"apple",
			"stonks":"3.8e13",
			"employees":"1.3e5",
			"description":"iPhone2049S SE+ with thirteen additional cameras",
			'logo': 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg',
		},
		{"id":45678,
			"name":"tesla",
			"stonks":"3.9e10",
			"employees":"4.5e4",
			"description":"electric bots",
			'logo': 'https://i.pinimg.com/originals/1d/3b/1f/1d3b1f99a82f0c6086f9011a5432d97f.png',
		},
		{"id":56789,
			"name":"google",
			"stonks":"4.8e12",
			"employees":"1.0e5",
			"description":"big brother",
			'logo': 'https://pngimg.com/uploads/google/google_PNG19644.png',
		},
		{"id":67890,
			"name":"facebook",
			"stonks":"2.6e10",
			"employees":"4.0e4",
			"description":"like a book with faces",
			'logo': 'https://logodownload.org/wp-content/uploads/2014/09/facebook-logo-1.png',
		},
		{"id":78901,
			"name":"oracle",
			"stonks":"1.4e11",
			"employees":"1.4e6",
			"description":"2 million devices",
			'logo': 'https://1000logos.net/wp-content/uploads/2017/04/Oracle-Logo.png',
		},
		{"id":15973,
			"name":"Trump Sales and Leasing",
			"stonks":"4.2e11",
			"employees":"3.0e3",
			"description":"sells things with Trump’s name on it",
			'logo': 'https://i.ya-webdesign.com/images/trump-pence-logo-png-2.png',
		},
		{"id":89012,
			"name":"berkshire hathaway",
			"stonks":"4.2e11",
			"employees":"389000",
			"description":"stonks",
			'logo': 'https://seeklogo.com/images/B/berkshire-hathaway-logo-766AFB8984-seeklogo.com.png',
		},
		{"id":90123,
			"name":"LVMH moet hennessy",
			"stonks":"4.2e11",
			"employees":"136000",
			"description":"rich french bois",
			'logo': 'https://logos-download.com/wp-content/uploads/2016/06/LVMH_logo_logotype_Mo%C3%ABt_Hennessy_Louis_Vuitton.png',
		},
		{"id":01234,
			"name":"zara",
			"stonks":"4.2e11",
			"employees":"174000",
			"description":"dress me up like one of your french girls",
			'logo':'https://upload.wikimedia.org/wikipedia/commons/f/fd/Zara_Logo.svg',
		},
		{"id":13579,
			"name":"america movil",
			"stonks":"4.2e11",
			"employees":"189000",
			"description":"el telecom de meheeko",
			'logo': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/28/America_Movil1.svg/1200px-America_Movil1.svg.png',
		},
		{"id":24680,
			"name":"reliance limited",
			"stonks":"4.2e11",
			"employees":"29000",
			"description":"rich indian bois",
			'logo': 'https://logodownload.org/wp-content/uploads/2019/10/reliance-industries-logo-1.png',
		},
		{"id":88888,
			"name":"blue origin",
			"stonks":"4.2e11",
			"employees":"2600",
			"description":"spaaaaccccceeee",
			'logo': 'https://i1.wp.com/spacenews360.com/wp-content/uploads/2017/12/blue-origin-logo.png?fit=985%2C522&ssl=1',
		},
		{"id":59270,
		 "name":"spaceX",
	 	 "stonks":"4.3e11",
	 	 "employees":"7000",
	   "description":"spaaaaccccceeee #2",
		 'logo':'https://www.stickpng.com/assets/images/5842a770a6515b1e0ad75afe.png',
	 },
	]
};
